---
# update apt package
    - name: Update apt cache 
      apt:
        update_cache: yes

# install Java 
    - name: Install OpenJDK 
      apt:
        name: openjdk-11-jdk
        state: present

# Jenkins installation
    - name: ensure the jenkins apt repository key is installed
      apt_key: url=https://pkg.jenkins.io/debian/jenkins.io-2023.key state=present

    - name: ensure the repository is configured
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
        state: present

    - name: ensure jenkins is installed
      apt: 
        name: jenkins 
        update_cache: yes

# Enable the Jenkins service to start at boot
    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
# Start Jenkins as a service
    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
#Check Jenkins service status
    - name: Check Jenkins service status
      shell: systemctl is-active jenkins
      register: jenkins_status
# print jenkins status
    - name: print jenkins status
      debug:
        var: jenkins_status.stdout


# get jenkins initial password in initialAdminPassword
    - name: Fetch Jenkins password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: jenkins_initial_password
# print jenkins initial password
    - name: print jenkins password
      debug:
        var: jenkins_initial_password.stdout