---
- name: Add Helm Stable Charts repository
  helm_repository:
    name: stable
    url: https://charts.helm.sh/stable
    state: present

- name: Add Prometheus Community Charts repository
  helm_repository:
    name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
    state: present

- name: Create Prometheus namespace in Kubernetes
  kubernetes:
    api_version: v1
    kind: Namespace
    metadata:
      name: prometheus
    state: present

- name: Install Prometheus using Helm chart
  helm_chart:
    name: prometheus
    namespace: prometheus
    chart: prometheus-community/kube-prometheus-stack
    # Consider adding values YAML for specific configuration

- name: Get status of Pods in Prometheus namespace
  kubernetes:
    api_version: v1
    kind: Pod
    metadata:
      namespace: prometheus
  register: prometheus_pods

